---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
```

# calculate model and data confidence intervals
```{r}
calc_data_conf_int_preVac <- function(post_data, data_size){
  sample_reps <- 1000
  confible_sample <- t(rmultinom(n = sample_reps, size = data_size,  prob = post_data))
  return(credible_sample)
}


calc_model_conf_int_minusPre <- function(sim_model, data_size, credible_sample_pre_data){
  sample_reps <- 1000
  credible_sample <- array(NA, dim = c(nrow(sim_model) * sample_reps, ncol(sim_model)))
  for (i in 1:nrow(sim_model)) {
    credible_sample[(sample_reps *(i-1)+1):(sample_reps *(i)),] <- t(rmultinom(n = sample_reps, size = data_size,  prob = sim_model[i,]))
  }
  mean_credible_sample <- apply(credible_sample,2,mean)/data_size
  
  mean_credible_sample_pre_data <- apply(credible_sample_pre_data,2,mean)/data_size
  
  mean_credible_sample <- mean_credible_sample - mean_credible_sample_pre_data
  percentile95_up_credible_sample <- apply((credible_sample - rep(credible_sample_pre_data, each = nrow(sim_model))), 2,quantile,.975)/data_size
  percentile95_low_credible_sample <- apply((credible_sample - rep(credible_sample_pre_data, each = nrow(sim_model))),2,quantile,.025)/data_size
  return(list(mean_credible_sample, percentile95_up_credible_sample, percentile95_low_credible_sample))
}

calc_data_conf_int_minusPre <- function(post_data, data_size, credible_sample_pre_data){
  sample_reps <- 1000
  credible_sample <- t(rmultinom(n = sample_reps, size = data_size,  prob = post_data))
  mean_credible_sample <- apply(credible_sample,2,mean)/data_size
  
  mean_credible_sample_pre_data <- apply(credible_sample_pre_data,2,mean)/data_size
  
  mean_credible_sample <- mean_credible_sample - mean_credible_sample_pre_data
  percentile95_up_credible_sample <- apply(credible_sample - credible_sample_pre_data,2,quantile,.975)/data_size
  percentile95_low_credible_sample <- apply(credible_sample - credible_sample_pre_data,2,quantile,.025)/data_size
  return(list(mean_credible_sample, percentile95_up_credible_sample, percentile95_low_credible_sample))
}
```

# calculate VT, NVT, and mixed information for GPSCs
```{r}
calc_VTNVT_cluster_info <- function(seq_cluster_data){
  cluster_VTs <- rep("NVT", length(unique(seq_cluster_data$GPSC)))
  names(cluster_VTs) <- unique(seq_cluster_data$GPSC)
  for (i in 1:length(unique(seq_cluster_data$GPSC))) {
    count_vts <- 0
    count_in_cluster <- length(which(seq_cluster_data$GPSC == unique(seq_cluster_data$GPSC)[i]))
    for (j in which(seq_cluster_data$GPSC == unique(seq_cluster_data$GPSC)[i])) {
      if(seq_cluster_data$VT[j] == "VT"){
        count_vts <- count_vts + 1
      }
    }
    if(count_vts == count_in_cluster){
      cluster_VTs[i] <- "VT"
    } else if(count_vts == 0){
      cluster_VTs[i] <- "NVT"
    } else{
      cluster_VTs[i] <- "mixed"
    }
  }
  cluster_VTs
}
```

# function for plotting data and model GPSC change
```{r}
create_conf_int_plot_change_sorted_GPSC <- function(post_VT_data, NFDS_model_out, seq_cluster_data, output_location, preVac_data, minmax){
  # calculate confidence intervals for data, NFDS model output, and null model output
  data_conf_int_pre <- calc_data_conf_int_preVac(preVac_data, sum(post_VT_data))
  data_conf_int <- calc_data_conf_int_minusPre(post_VT_data, sum(post_VT_data), data_conf_int_pre)
  NFDS_conf_int <- calc_model_conf_int_minusPre(NFDS_model_out, sum(post_VT_data), data_conf_int_pre)
  
  # calculate which models are VT, NVT, or mixed
  cluster_VTs_info <- calc_VTNVT_cluster_info(seq_cluster_data)
  
  # choose to display only clusters that are at least at 1% frequency at the beginning
  no_small_clusters <- which(preVac_data/sum(preVac_data) > 0.01)
  
  # create df for ggplot
  data_and_model_with_errors_and_null_ModelSample <- data.frame(
  cluster=rep(((unique(seq_cluster_data$GPSC))[no_small_clusters]),2),
  xvals = rep(1:length(unique(seq_cluster_data$GPSC)[no_small_clusters]),2),
  Group = c(rep("Data",length(unique(seq_cluster_data$GPSC)[no_small_clusters])),rep("NFDS Model",length(unique(seq_cluster_data$GPSC)[no_small_clusters]))),
  VT = rep(cluster_VTs_info[no_small_clusters],2),
  values=c(data_conf_int[[1]][no_small_clusters], NFDS_conf_int[[1]][no_small_clusters]),
  upper=c(data_conf_int[[2]][no_small_clusters], NFDS_conf_int[[2]][no_small_clusters]),
  lower = c(data_conf_int[[3]][no_small_clusters], NFDS_conf_int[[3]][no_small_clusters]))
  
  # compute order by frequency changes
  # VTs and NVTs separately
  data_and_model_with_errors_and_null_ModelSample_NVT <- data_and_model_with_errors_and_null_ModelSample[which(data_and_model_with_errors_and_null_ModelSample$VT=="NVT"),]
  data_and_model_with_errors_and_null_ModelSample_NVT$xvals <- rep(1:(nrow(data_and_model_with_errors_and_null_ModelSample_NVT)/2),2)
  data_and_model_with_errors_and_null_ModelSample_VT <- data_and_model_with_errors_and_null_ModelSample[which(data_and_model_with_errors_and_null_ModelSample$VT=="VT"),]
  data_and_model_with_errors_and_null_ModelSample_mixed <- data_and_model_with_errors_and_null_ModelSample[which(data_and_model_with_errors_and_null_ModelSample$VT=="mixed"),]
  data_and_model_with_errors_and_null_ModelSample_mixed$xvals <- rep(1:(nrow(data_and_model_with_errors_and_null_ModelSample_mixed)/2),2)
  
  level_order_NVT <- order(data_and_model_with_errors_and_null_ModelSample_NVT$values[which(data_and_model_with_errors_and_null_ModelSample_NVT$Group == "Data")], decreasing = TRUE)
  level_order_mixed <- order(data_and_model_with_errors_and_null_ModelSample_mixed$values[which(data_and_model_with_errors_and_null_ModelSample_mixed$Group == "Data")], decreasing = TRUE)
 
  # make NVT plot

  plot_NVT <- ggplot(data_and_model_with_errors_and_null_ModelSample_NVT, aes(y=values, x=factor(xvals,level = level_order_NVT), group = Group, color = Group)) + 
    geom_hline(yintercept = 0, linetype="dashed") +
    geom_point(position = position_dodge(.5), stat="identity",size = 2.5) +
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.5, alpha=0.9, linewidth=1,position=position_dodge(.5)) +
  scale_x_discrete("Strains", breaks = 1:(length(which(cluster_VTs_info[no_small_clusters]=="NVT"))), labels = names(cluster_VTs_info[no_small_clusters])[which(cluster_VTs_info[no_small_clusters]=="NVT")])+
  scale_color_manual(values = c("black", "#0072B2"),labels = c("Data", "NFDS Model")) +
  labs(x = "Strains", y = "Frequency") +
  ggtitle("NVT Clusters Data vs. NFDS Model vs. Neutral Model\n with 95% multinomial confidence intervals") +  # Add the plot title
  theme(panel.background = element_rect(fill = "white",),
        panel.grid = element_line(color = "grey"),text = element_text(size = 20)) +
  ylim(-minmax, minmax)
  
    ggsave(plot_NVT, 
      filename = paste(output_location,"Change_NVT_DatavsNFDS.pdf",sep = ""),   # The directory and file name you want to save the file in
      device = "pdf",
      width = length(level_order_NVT), # The width of the plot in inches
      height = 6)
  
  # make VT plot
  if(nrow(data_and_model_with_errors_and_null_ModelSample_VT)>0){
    data_and_model_with_errors_and_null_ModelSample_VT$xvals <- rep(1:(nrow(data_and_model_with_errors_and_null_ModelSample_VT)/2),2)
    level_order_VT <- order(data_and_model_with_errors_and_null_ModelSample_VT$values[which(data_and_model_with_errors_and_null_ModelSample_VT$Group == "Data")], decreasing = TRUE)

    plot_VT <- ggplot(data_and_model_with_errors_and_null_ModelSample_VT, aes(y=values, x=factor(xvals,level = level_order_VT), group = Group, color = Group)) +  
    geom_hline(yintercept = 0, linetype="dashed") +
    geom_point(position = position_dodge(.5), stat="identity",size = 2.5) +
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.5, alpha=0.9, linewidth=1,position=position_dodge(.5)) +
    scale_x_discrete("Strains", breaks = 1:(length(which(cluster_VTs_info[no_small_clusters]=="VT"))), labels = names(cluster_VTs_info[no_small_clusters])[which(cluster_VTs_info[no_small_clusters]=="VT")])+
    scale_color_manual(values = c("black", "#0072B2"),labels = c("Data", "NFDS Model")) +
    labs(x = "Strains", y = "Frequency") +
    ggtitle("VT Clusters Data vs. NFDS Model vs. Neutral Model\n with 95% multinomial confidence intervals") +  # Add the plot title
    theme(panel.background = element_rect(fill = "white",),
        panel.grid = element_line(color = "grey"),text = element_text(size = 20)) +
    ylim(-minmax, minmax)

    ggsave(plot_VT, 
      filename = paste(output_location,"Change_VT_DatavsNFDS.pdf",sep = ""),   # The directory and file name you want to save the file in
      device = "pdf",
      width = length(level_order_VT), # The width of the plot in inches
      height = 6)
  }
  
  # make mixed plot

  plot_mixed <- ggplot(data_and_model_with_errors_and_null_ModelSample_mixed, aes(y=values, x=factor(xvals,level = level_order_mixed), group = Group, color = Group)) +  
    geom_hline(yintercept = 0, linetype="dashed") +
    geom_point(position = position_dodge(.5), stat="identity",size = 2.5) +
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.5, alpha=0.9, linewidth=1,position=position_dodge(.5)) +
  scale_x_discrete("Strains", breaks = 1:(length(which(cluster_VTs_info[no_small_clusters]=="mixed"))), labels = names(cluster_VTs_info[no_small_clusters])[which(cluster_VTs_info[no_small_clusters]=="mixed")])+
  scale_color_manual(values = c("black", "#0072B2"),labels = c("Data", "NFDS Model")) +
  labs(x = "Strains", y = "Frequency") +
  ggtitle("Mixed Clusters Data vs. NFDS Model vs. Neutral Model\n with 95% multinomial confidence intervals") +  # Add the plot title
  theme(panel.background = element_rect(fill = "white",),
        panel.grid = element_line(color = "grey"),text = element_text(size = 20)) +
  ylim(-minmax, minmax)
  
  ggsave(plot_mixed, 
    filename = paste(output_location,"Change_Mixed_DatavsNFDS.pdf",sep = ""),   # The directory and file name you want to save the file in
    device = "pdf",
    width = length(level_order_mixed), # The width of the plot in inches
    height = 6)
}
```

# function for plotting data and model serotype change
```{r}
create_conf_int_plot_change_sorted_sero <- function(post_VT_data, NFDS_model_out, seq_cluster_data, output_location, preVac_data, minmax, VT_dict){
  # calculate confidence intervals for data, NFDS model output, and null model output
  data_conf_int_pre <- calc_data_conf_int_preVac(preVac_data, sum(post_VT_data))
  data_conf_int <- calc_data_conf_int_minusPre(post_VT_data, sum(post_VT_data), data_conf_int_pre)
  NFDS_conf_int <- calc_model_conf_int_minusPre(NFDS_model_out, sum(post_VT_data), data_conf_int_pre)
  
  # calculate which models are VT, NVT, or mixed
  cluster_VTs_info <- rep("NVT", length(VT_dict))
  cluster_VTs_info[which(VT_dict == 1) ] <- "VT"
  names(cluster_VTs_info) <- names(VT_dict)
  
  # choose to display only clusters that are at least at 1% frequency at the beginning
  no_small_clusters <- which(preVac_data/sum(preVac_data) > 0.01)
  
  # create df for ggplot
  data_and_model_with_errors_and_null_ModelSample <- data.frame(
  cluster=rep(((unique(seq_cluster_data$Serotype))[no_small_clusters]),2),
  xvals = rep(1:length(unique(seq_cluster_data$Serotype)[no_small_clusters]),2),
  Group = c(rep("Data",length(unique(seq_cluster_data$Serotype)[no_small_clusters])),rep("NFDS Model",length(unique(seq_cluster_data$Serotype)[no_small_clusters]))),
  VT = rep(cluster_VTs_info[no_small_clusters],2),
  values=c(data_conf_int[[1]][no_small_clusters], NFDS_conf_int[[1]][no_small_clusters]),
  upper=c(data_conf_int[[2]][no_small_clusters], NFDS_conf_int[[2]][no_small_clusters]),
  lower = c(data_conf_int[[3]][no_small_clusters], NFDS_conf_int[[3]][no_small_clusters]))
  
  # compute order by frequency changes
  # VTs and NVTs separately
  data_and_model_with_errors_and_null_ModelSample_NVT <- data_and_model_with_errors_and_null_ModelSample[which(data_and_model_with_errors_and_null_ModelSample$VT=="NVT"),]
  data_and_model_with_errors_and_null_ModelSample_NVT$xvals <- rep(1:(nrow(data_and_model_with_errors_and_null_ModelSample_NVT)/2),2)
  data_and_model_with_errors_and_null_ModelSample_VT <- data_and_model_with_errors_and_null_ModelSample[which(data_and_model_with_errors_and_null_ModelSample$VT=="VT"),]
  
  level_order_NVT <- order(data_and_model_with_errors_and_null_ModelSample_NVT$values[which(data_and_model_with_errors_and_null_ModelSample_NVT$Group == "Data")], decreasing = TRUE)
 
  # make NVT plot

  plot_NVT <- ggplot(data_and_model_with_errors_and_null_ModelSample_NVT, aes(y=values, x=factor(xvals,level = level_order_NVT), group = Group, color = Group)) + 
    geom_hline(yintercept = 0, linetype="dashed") +
    geom_point(position = position_dodge(.5), stat="identity",size = 2.5) +
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.5, alpha=0.9, linewidth=1,position=position_dodge(.5)) +
  scale_x_discrete("Serotype", breaks = 1:(length(which(cluster_VTs_info[no_small_clusters]=="NVT"))), labels = names(cluster_VTs_info[no_small_clusters])[which(cluster_VTs_info[no_small_clusters]=="NVT")])+
  scale_color_manual(values = c("black", "#0072B2"),labels = c("Data", "NFDS Model")) +
  labs(x = "Serotype", y = "Frequency") +
  ggtitle("NVT Clusters Data vs. NFDS Model vs. Neutral Model\n with 95% multinomial confidence intervals") +  # Add the plot title
  theme(panel.background = element_rect(fill = "white",),
        panel.grid = element_line(color = "grey"),text = element_text(size = 20)) +
  ylim(-minmax, minmax)
  
    ggsave(plot_NVT, 
      filename = paste(output_location,"SeroChange_NVT_DatavsNFDS.pdf",sep = ""),   # The directory and file name you want to save the file in
      device = "pdf",
      width = length(level_order_NVT), # The width of the plot in inches
      height = 6)
  
  # make VT plot
  if(nrow(data_and_model_with_errors_and_null_ModelSample_VT)>0){
    data_and_model_with_errors_and_null_ModelSample_VT$xvals <- rep(1:(nrow(data_and_model_with_errors_and_null_ModelSample_VT)/2),2)
    level_order_VT <- order(data_and_model_with_errors_and_null_ModelSample_VT$values[which(data_and_model_with_errors_and_null_ModelSample_VT$Group == "Data")], decreasing = TRUE)

    plot_VT <- ggplot(data_and_model_with_errors_and_null_ModelSample_VT, aes(y=values, x=factor(xvals,level = level_order_VT), group = Group, color = Group)) +  
    geom_hline(yintercept = 0, linetype="dashed") +
    geom_point(position = position_dodge(.5), stat="identity",size = 2.5) +
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.5, alpha=0.9, linewidth=1,position=position_dodge(.5)) +
    scale_x_discrete("Serotype", breaks = 1:(length(which(cluster_VTs_info[no_small_clusters]=="VT"))), labels = names(cluster_VTs_info[no_small_clusters])[which(cluster_VTs_info[no_small_clusters]=="VT")])+
    scale_color_manual(values = c("black", "#0072B2"),labels = c("Data", "NFDS Model")) +
    labs(x = "Serotype", y = "Frequency") +
    ggtitle("VT Clusters Data vs. NFDS Model vs. Neutral Model\n with 95% multinomial confidence intervals") +  # Add the plot title
    theme(panel.background = element_rect(fill = "white",),
        panel.grid = element_line(color = "grey"),text = element_text(size = 20)) +
    ylim(-minmax, minmax)

    ggsave(plot_VT, 
      filename = paste(output_location,"SeroChange_VT_DatavsNFDS.pdf",sep = ""),   # The directory and file name you want to save the file in
      device = "pdf",
      width = length(level_order_VT), # The width of the plot in inches
      height = 6)
  }
}
```

# read in forward simulation of model and data and cluster information (from PopPUNK) for US
```{r}
params_4_model_data_rel_sero <- readRDS("params_4_model_data_rel_sero.rds")# serotype frequencies from model simulation (created with file "SimulateModelWithMCMCEstimates.R")
params_4_model_data_rel_GPSC <- readRDS("params_4_model_data_rel_GPSC.rds") # GPSC frequencies from model simulation (created with file "SimulateModelWithMCMCEstimates.R")

# pre-vac GPSC freqs
GPSC_data_preVac <- readRDS(file = "GPSC_count_1.rds")
# post-vac GPSC freqs
GPSC_data_postVac <- readRDS(file = "GPSC_count_3.rds")
PopPUNK_clusters <- read.csv("poppunk_clusters_external_clusters.csv")
colnames(PopPUNK_clusters)[2] <- "GPSC"

location_for_plots <- "./" # location for outputting the plots to
minmax <- 0.15 # range for plot 

# vector with info whether serotypes are affected by vaccine
SeroVT_dict <- readRDS("SeroVT.rds")

MetaData <- read.csv("MetaData.csv") # maybe change to readr
Serotype_dict <- MetaData$Serotype
names(Serotype_dict) <- MetaData$filename
PopPUNK_clusters$Serotype <- Serotype_dict[PopPUNK_clusters$Taxon]
names(SeroVT_dict) <- unique(PopPUNK_clusters$Serotype)

VT_dict <- MetaData$`Vaccine.Type`
names(VT_dict) <- MetaData$filename
PopPUNK_clusters$VT <- VT_dict[PopPUNK_clusters$Taxon]

# preVac sero frequencies
preVac_sero <- readRDS("PP_mass_sero_freq_1.rds") # doesn't exist, still need to implement
postVac_sero <- readRDS("PP_mass_sero_freq_3.rds") # # doesn't exist, still need to implement

```

# make serotype change plot
```{r}
# this one is not working yet, will fix tmr
create_conf_int_plot_change_sorted_sero(US_sero_freq_2007, US_params_4_model_data_rel_sero, PopPUNK_clusters, location_for_plots_sero, US_preVac_sero, minmax_US_sero, SeroVT_dict)
```

# make GPSC change plot
```{r}
create_conf_int_plot_change_sorted_GPSC(GPSC_data_postVac, params_4_model_data_rel_GPSC, PopPUNK_clusters, location_for_plots, GPSC_data_preVac, minmax)
```

