---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
# read in pre-processed fits for simulation (create three independent fits, then calculated parameter mean and 95-percentiles)

sim_fit_m_1 <- read.csv("joined_mcmc_param_fits_sampleSize3_m_2.csv")[,-1]
sim_fit_m_2 <- read.csv("joined_mcmc_param_fits_sampleSize3_m_2_v2.csv")[,-1]
sim_fit_m_3 <- read.csv("joined_mcmc_param_fits_sampleSize3_m_2_v3.csv")[,-1]

sim_fit_v_1 <- read.csv("joined_mcmc_param_fits_sampleSize3_v_2.csv")[,-1]
sim_fit_v_2 <- read.csv("joined_mcmc_param_fits_sampleSize3_v_2_v2.csv")[,-1]
sim_fit_v_3 <- read.csv("joined_mcmc_param_fits_sampleSize3_v_2_v3.csv")[,-1]

sim_fit_sigmaf_1 <- read.csv("joined_mcmc_param_fits_sampleSize3_sigmaf_2.csv")[,-1]
sim_fit_sigmaf_2 <- read.csv("joined_mcmc_param_fits_sampleSize3_sigmaf_2_v2.csv")[,-1]
sim_fit_sigmaf_3 <- read.csv("joined_mcmc_param_fits_sampleSize3_sigmaf_2_v3.csv")[,-1]

sim_fit_propf_1 <- read.csv("joined_mcmc_param_fits_sampleSize3_propf_2.csv")[,-1]
sim_fit_propf_2 <- read.csv("joined_mcmc_param_fits_sampleSize3_propf_2_v2.csv")[,-1]
sim_fit_propf_3 <- read.csv("joined_mcmc_param_fits_sampleSize3_propf_2_v3.csv")[,-1]
```

```{r}
# calculate mean of means for each parameter

sim_fit_m_mean <- cbind(sim_fit_m_1$params, sim_fit_m_1$population, sapply(c(sim_fit_m_1$mean, sim_fit_m_2$mean, sim_fit_m_3$mean), mean), sapply(c(sim_fit_m_1$lower, sim_fit_m_2$lower, sim_fit_m_3$lower), mean), sapply(c(sim_fit_m_1$upper, sim_fit_m_2$upper, sim_fit_m_3$upper), mean))
sim_fit_v_mean <- cbind(sim_fit_v_1$params, sim_fit_v_1$population, sapply(c(sim_fit_v_1$mean, sim_fit_v_2$mean, sim_fit_v_3$mean), mean), sapply(c(sim_fit_v_1$lower, sim_fit_v_2$lower, sim_fit_v_3$lower), mean), sapply(c(sim_fit_v_1$upper, sim_fit_v_2$upper, sim_fit_v_3$upper), mean))
sim_fit_sigmaf_mean <- cbind(sim_fit_sigmaf_1$params, sim_fit_sigmaf_1$population, sapply(c(sim_fit_sigmaf_1$mean, sim_fit_sigmaf_2$mean, sim_fit_sigmaf_3$mean), mean), sapply(c(sim_fit_sigmaf_1$lower, sim_fit_sigmaf_2$lower, sim_fit_sigmaf_3$lower), mean), sapply(c(sim_fit_sigmaf_1$upper, sim_fit_sigmaf_2$upper, sim_fit_sigmaf_3$upper), mean))
sim_fit_propf_mean <- cbind(sim_fit_propf_1$params, sim_fit_propf_1$population, sapply(c(sim_fit_propf_1$mean, sim_fit_propf_2$mean, sim_fit_propf_3$mean), mean), sapply(c(sim_fit_propf_1$lower, sim_fit_propf_2$lower, sim_fit_propf_3$lower), mean), sapply(c(sim_fit_propf_1$upper, sim_fit_propf_2$upper, sim_fit_propf_3$upper), mean))

colnames(sim_fit_m_mean) <- colnames(sim_fit_m_1)[1:5]
colnames(sim_fit_v_mean) <- colnames(sim_fit_m_1)[1:5]
colnames(sim_fit_sigmaf_mean) <- colnames(sim_fit_m_1)[1:5]
colnames(sim_fit_propf_mean) <- colnames(sim_fit_m_1)[1:5]
```

# next steps: make new plot with means
# make joint df with means of all params
# use this df for running simulation analysis on cluster (simulate model forward with fitted parameters and then compare to original trajectory)

```{r}
sim_fit_param_means <- cbind(sim_fit_m_mean[,1:3], sim_fit_v_mean[,3], sim_fit_sigmaf_mean[,3], sim_fit_propf_mean[,3])
colnames(sim_fit_param_means) <- c(colnames(sim_fit_m_mean)[1:2], "m", "v", "sigmaf", "propf")
#write.csv(sim_fit_param_means, "parameter_means_fits_to_simulation.csv", row.names = TRUE)
write.table(sim_fit_param_means, "parameter_means_fits_to_simulation.tsv", row.names = TRUE, sep='\t', col.names = FALSE, quote=FALSE)
```

